
$(document).ready(function(){
        $("#jumbotron2").hide();
        $("#jumbotron3").hide();
        $("#jumbotron4").hide();
        $("#jumbotron5").hide();
        $("#jumbotron6").hide();
        $("#id-jus").click(function(){
          $("#jumbotron2").toggle();
          $("#jumbotron3").hide();
          $("#jumbotron4").hide();
          $("#jumbotron5").hide();
          $("#jumbotron6").hide(); 
        });
        $("#id-caffe").click(function(){
          $("#jumbotron3").toggle();
          $("#jumbotron2").hide();
          $("#jumbotron4").hide();
          $("#jumbotron5").hide();
          $("#jumbotron6").hide();
        });
        $("#id-petit-dejeuner").click(function(){
          $("#jumbotron5").toggle();
          $("#jumbotron3").hide();
          $("#jumbotron2").hide();
          $("#jumbotron4").hide();
          $("#jumbotron6").hide();
        });
        $("#id-croisant").click(function(){
          $("#jumbotron6").toggle();
          $("#jumbotron3").hide();
          $("#jumbotron4").hide();
          $("#jumbotron2").hide();
          $("#jumbotron5").hide();
        });
        $("#id-the").click(function(){
          $("#jumbotron4").toggle();
          $("#jumbotron3").hide();
          $("#jumbotron6").hide();
          $("#jumbotron5").hide();
          $("#jumbotron2").hide();
        });
    });